### ISSUE TITLE
cython dependency.

### ISSUE THREAD

**Issue by rzu512** [dask/crick#13]
When I try to install crick by pip3, pip3 doesn't install Cython automatically.
```
$ pip3 install crick --user

Collecting crick
  Using cached crick-0.0.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-y1mcfhjt/crick/setup.py", line 7, in <module>
        from Cython.Build import cythonize
    ModuleNotFoundError: No module named 'Cython'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-y1mcfhjt/crick/
```

**Comment by jcrist** [comment]
This is a bit tricky to do cleanly due to how `setup.py` scripts are run. I'll resolve this for sure before the next release, but the resolution might be just to remove cython completely (see #17).

Note that binary releases are available for all OS's with conda, and for osx (currently) on pypi. A manylinux and windows build setup could be done for pypi as well, but it's not high priority for me.

**Comment by shughes-uk** [comment]
@jcrist poke

**Comment by MuellerSeb** [comment]
This is solved with the pyproject.toml that defines build time dependencies.

Added here: https://github.com/dask/crick/pull/39

**Comment by milesgranger** [comment]
Thanks, @MuellerSeb!
